### ISSUE TITLE
AssertionError: Your gridspacing is too large.

### ISSUE THREAD

**Issue by magdalos** [Niolon/XHARPy#1]
[pHAR_gpaw_issue.zip](https://github.com/Niolon/XHARPy/files/11311679/pHAR_gpaw_issue.zip)

Hi Niklas,

This is the 1st of the errors that I got trying to run refinement using GPAW for a Cu MOF. Files used to run refinement are attached.

Best,
Magda

**Comment by Niolon** [comment]
Will be handled in issue #2

**Comment by Niolon** [comment]
Btw in my trial run yesterday, gpaw seemed to have some convergence problems when recycling the density.  I would advise putting the reload_step in the refinement_dict to a number that is never reached such as 10000.
