### ISSUE TITLE
missing residual density information in the xharpy.cif file

### ISSUE THREAD

**Issue by magdalos** [Niolon/XHARPy#3]
Hi Niklas,

I performed HAR for the same structure using a desktop computer and using a computer cluster. In the xharpy.cif file produced on the cluster the following fields have no values:

_refine_diff_density_max           .
_refine_diff_density_min           .
_refine_diff_density_rms           .

I have attached the folders with the results of calculations on both computers (without the .gpw files).

Best wishes,
Magda

[pHAR_gpaw_AFIX1_H004_iso.zip](https://github.com/Niolon/XHARPy/files/12182282/pHAR_gpaw_AFIX1_H004_iso.zip)
[pHAR_gpaw_AFIX1_H004_iso_cluster.zip](https://github.com/Niolon/XHARPy/files/12182283/pHAR_gpaw_AFIX1_H004_iso_cluster.zip)

**Comment by Niolon** [comment]
Hi Magda, 
the difference electron densities are added with the last command in the script (add_density_entries_from_fcf) using the cctbx. If you look into your slurm output from the cluster you can see that cctbx was not installed on the cluster (iotbx is missing). Fortunately you can run the command standalone without any of the calculations done before, either on the cluster or just your desktop.
Best Niklas
